name: Michael Pollind
description: >
    Michael Pollind

master_repo: false
url: "https://pollend.github.io/"
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 4

logo:             logo.png
disqus_shortname:

rtl: false
owner:
  name:           Michael Pollind
  avatar:         "https://avatars1.githubusercontent.com/u/854359?s=460&v=4"
  email:          "polli104@mail.chapman.edu"
  # Social networking links used in footer. Update and remove as you like.
  twitter: MPollind
  github: https://github.com/pollend
  stackexchange:
  linkedin: www.linkedin.com/in/michaelpollind
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
